export const classifiedChoices = [
  {
    desc: "P-B related phonemes",
    choices: [
      { id: "0070", symbol: "p" },
      { id: "0062", symbol: "b" },
      { id: "006D", symbol: "m" },
      { id: "0076", symbol: "v" },
    ],
  },
  {
    desc: "T-D related phonemes",
    choices: [
      { id: "0074", symbol: "t" },
      { id: "0062", symbol: "d" },
      { id: "0256", symbol: "ɖ" },
      { id: "0288", symbol: "ʈ" },
    ],
  },
  {
    desc: "M-N related phonemes",
    choices: [
      { id: "006D", symbol: "m" },
      { id: "006E", symbol: "n" },
      { id: "0273", symbol: "ɳ" },
      { id: "0272", symbol: "ɲ" },
    ],
  },
  {
    desc: "V related phonemes",
    choices: [
      { id: "03B2", symbol: "β" },
      { id: "028B", symbol: "ʋ" },
      { id: "0076", symbol: "v" },
      { id: "0076", symbol: "v" },
    ],
  },
  {
    desc: "F related phonemes",
    choices: [
      { id: "0066", symbol: "f" },
      { id: "0278", symbol: "ɸ" },
      { id: "03B8", symbol: "θ" },
      { id: "0073", symbol: "s" },
    ],
  },
  {
    desc: "K-G related phonemes",
    choices: [
      { id: "006B", symbol: "k" },
      { id: "0063", symbol: "c" },
      { id: "0071", symbol: "q" },
      { id: "0261", symbol: "g" },
    ],
  },
  {
    desc: "G related phonemes",
    choices: [
      { id: "0261", symbol: "g" },
      { id: "025F", symbol: "ɟ" },
      { id: "0262", symbol: "ɢ" },
      { id: "014B", symbol: "ŋ" },
      { id: "0280", symbol: "ʀ" },
      { id: "0281", symbol: "ʁ" },
      { id: "0263", symbol: "ɣ" },
    ],
  },
  {
    desc: "R-L related phonemes",
    choices: [
      { id: "0072", symbol: "r" },
      { id: "027E", symbol: "ɾ" },
      { id: "0279", symbol: "ɹ" },
      { id: "027D", symbol: "ɽ" },
      { id: "006C", symbol: "l" },
      { id: "026D", symbol: "ɭ" },
    ],
  },
  {
    desc: "S related phonemes",
    choices: [
      { id: "0073", symbol: "s" },
      { id: "0283", symbol: "ʃ" },
      { id: "03B8", symbol: "θ" },
      { id: "0282", symbol: "ʂ" },
      { id: "00E7", symbol: "ç" },
    ],
  },
  {
    desc: "Z related phonemes",
    choices: [
      { id: "007A", symbol: "z" },
      { id: "00F0", symbol: "ð" },
      { id: "0292", symbol: "ʒ" },
      { id: "0290", symbol: "ʐ" },
    ],
  },
  {
    desc: "J related phonemes",
    choices: [
      { id: "006A", symbol: "j" },
      { id: "029D", symbol: "ʝ" },
      { id: "026E", symbol: "ɮ" },
      { id: "028E", symbol: "ʎ" },
      { id: "025F", symbol: "ɟ" },
    ],
  },
  {
    desc: "H related phonemes",
    choices: [
      { id: "0068", symbol: "h" },
      { id: "0078", symbol: "x" },
      { id: "026E", symbol: "χ" },
      { id: "0127", symbol: "ħ" },
      { id: "0266", symbol: "ɦ" },
    ],
  },
  {
    desc: "Special phonemes",
    choices: [
      { id: "0294", symbol: "ʔ" },
      { id: "0295", symbol: "ʕ" },
      { id: "0274", symbol: "ɴ" },
      { id: "0270", symbol: "ɰ" },
    ],
  },
]

export const symbols = [
  { symbol: "p", desc: "VOICELESS BILABIAL PLOSIVE", id: "0070" },
  { symbol: "b", desc: "VOICED BILABIAL PLOSIVE", id: "0062" },
  { symbol: "t", desc: "VOICELESS DENTAL/ALVEOLAR PLOSIVE", id: "0074" },
  { symbol: "d", desc: "VOICED DENTAL/ALVEOLAR PLOSIVE", id: "0064" },
  { symbol: "ʈ", desc: "VOICELESS RETROFLEX PLOSIVE", id: "0288" },
  { symbol: "ɖ", desc: "VOICED RETROFLEX PLOSIVE", id: "0256" },
  { symbol: "c", desc: "VOICELESS PALATAL PLOSIVE", id: "0063" },
  { symbol: "ɟ", desc: "VOICED PALATAL PLOSIVE", id: "025F" },
  { symbol: "k", desc: "VOICELESS VELAR PLOSIVE", id: "006B" },
  { symbol: "ɡ", desc: "VOICED VELAR PLOSIVE", id: "0261" },
  { symbol: "q", desc: "VOICELESS UVULAR PLOSIVE", id: "0071" },
  { symbol: "ɢ", desc: "VOICED UVULAR PLOSIVE", id: "0262" },
  { symbol: "ʔ", desc: "GLOTTAL PLOSIVE", id: "0294" },
  { symbol: "m", desc: "VOICED BILABIAL NASAL", id: "006D" },
  { symbol: "ɱ", desc: "VOICED LABIODENTAL NASAL", id: "0271" },
  { symbol: "n", desc: "VOICED DENTAL/ALVEOLAR NASAL", id: "006E" },
  { symbol: "ɳ", desc: "VOICED RETROFLEX NASAL", id: "0273" },
  { symbol: "ɲ", desc: "VOICED PALATAL NASAL", id: "0272" },
  { symbol: "ŋ", desc: "VOICED VELAR NASAL", id: "014B" },
  { symbol: "ɴ", desc: "VOICED UVULAR NASAL", id: "0274" },
  { symbol: "ʙ", desc: "VOICED BILABIAL TRILL", id: "0299" },
  { symbol: "r", desc: "VOICED DENTAL/ALVEOLAR TRILL", id: "0072" },
  { symbol: "ʀ", desc: "VOICED UVULAR TRILL", id: "0280" },
  { symbol: "ⱱ", desc: "VOICED LABIODENTAL FLAP", id: "2C71" },
  { symbol: "ɾ", desc: "VOICED DENTAL/ALVEOLAR TAP", id: "027E" },
  { symbol: "ɽ", desc: "VOICED RETROFLEX FLAP", id: "027D" },
  { symbol: "ɸ", desc: "VOICELESS BILABIAL FRICATIVE", id: "0278" },
  { symbol: "β", desc: "VOICED BILABIAL FRICATIVE", id: "03B2" },
  { symbol: "f", desc: "VOICELESS LABIODENTAL FRICATIVE", id: "0066" },
  { symbol: "v", desc: "VOICED LABIODENTAL FRICATIVE", id: "0076" },
  { symbol: "θ", desc: "VOICELESS DENTAL FRICATIVE", id: "03B8" },
  { symbol: "ð", desc: "VOICED DENTAL FRICATIVE", id: "00F0" },
  { symbol: "s", desc: "VOICELESS ALVEOLAR FRICATIVE", id: "0073" },
  { symbol: "z", desc: "VOICED ALVEOLAR FRICATIVE", id: "007A" },
  { symbol: "ʃ", desc: "VOICELESS POSTALVEOLAR FRICATIVE", id: "0283" },
  { symbol: "ʒ", desc: "VOICED POSTALVEOLAR FRICATIVE", id: "0292" },
  { symbol: "ʂ", desc: "VOICELESS RETROFLEX FRICATIVE", id: "0282" },
  { symbol: "ʐ", desc: "VOICED RETROFLEX FRICATIVE", id: "0290" },
  { symbol: "ç", desc: "VOICELESS PALATAL FRICATIVE", id: "00E7" },
  { symbol: "ʝ", desc: "VOICED PALATAL FRICATIVE", id: "029D" },
  { symbol: "x", desc: "VOICELESS VELAR FRICATIVE", id: "0078" },
  { symbol: "ɣ", desc: "VOICED VELAR FRICATIVE", id: "0263" },
  { symbol: "χ", desc: "VOICELESS UVULAR FRICATIVE", id: "03C7" },
  { symbol: "ʁ", desc: "VOICED UVULAR FRICATIVE", id: "0281" },
  { symbol: "ħ", desc: "VOICELESS PHARYNGEAL FRICATIVE", id: "0127" },
  { symbol: "ʕ", desc: "VOICED PHARYNGEAL FRICATIVE/APPROXIMANT", id: "0295" },
  { symbol: "h", desc: "VOICELESS GLOTTAL FRICATIVE", id: "0068" },
  { symbol: "ɦ", desc: "VOICED GLOTTAL FRICATIVE", id: "0266" },
  { symbol: "ɬ", desc: "VOICELESS DENTAL/ALVEOLAR LATERAL FRICATIVE", id: "026C" },
  { symbol: "ɮ", desc: "VOICED DENTAL/ALVEOLAR LATERAL FRICATIVE", id: "026E" },
  { symbol: "ʋ", desc: "VOICED LABIODENTAL APPROXIMANT", id: "028B" },
  { symbol: "ɹ", desc: "VOICED DENTAL/ALVEOLAR APPROXIMANT", id: "0279" },
  { symbol: "ɻ", desc: "VOICED RETROFLEX APPROXIMANT", id: "027B" },
  { symbol: "j", desc: "VOICED PALATAL APPROXIMANT", id: "006A" },
  { symbol: "ɰ", desc: "VOICED VELAR APPROXIMANT", id: "0270" },
  { symbol: "l", desc: "VOICED DENTAL/ALVEOLAR LATERAL APPROXIMANT", id: "006C" },
  { symbol: "ɭ", desc: "VOICED RETROFLEX LATERAL APPROXIMANT", id: "026D" },
  { symbol: "ʎ", desc: "VOICED PALATAL LATERAL APPROXIMANT", id: "028E" },
  { symbol: "ʟ", desc: "VOICED VELAR LATERAL APPROXIMANT", id: "029F" },
  { symbol: "ʘ", desc: "BILABIAL CLICK", id: "0298" },
  { symbol: "ɓ", desc: "VOICED BILABIAL IMPLOSIVE", id: "0253" },
  // { symbol: "ʼ", desc: "EJECTIVE", id: "02BC" },
  { symbol: "ǀ", desc: "DENTAL CLICK", id: "01C0" },
  { symbol: "ɗ", desc: "VOICED DENTAL/ALVEOLAR IMPLOSIVE", id: "0257" },
  { symbol: "pʼ", desc: "BILABIAL EJECTIVE", id: "0070 + 02BC" },
  { symbol: "ǃ", desc: "(POST)ALVEOLAR CLICK", id: "01C3" },
  { symbol: "ʄ", desc: "VOICED PALATAL IMPLOSIVE", id: "0284" },
  { symbol: "tʼ", desc: "DENTAL/ALVEOLAR EJECTIVE", id: "0074 + 02BC" },
  { symbol: "ǂ", desc: "PALATOALVEOLAR CLICK", id: "01C2" },
  { symbol: "ɠ", desc: "VOICED VELAR IMPLOSIVE", id: "0260" },
  { symbol: "kʼ", desc: "VELAR EJECTIVE", id: "006B + 02BC" },
  { symbol: "ǁ", desc: "ALVEOLAR LATERAL CLICK", id: "01C1" },
  { symbol: "ʛ", desc: "VOICED UVULAR IMPLOSIVE", id: "029B" },
  { symbol: "sʼ", desc: "ALVEOLAR FRICATIVE EJECTIVE", id: "0073 + 02BC" },
  { symbol: "ʍ", desc: "VOICELESS LABIAL-VELAR FRICATIVE", id: "028D" },
  { symbol: "ɕ", desc: "VOICELESS ALVEOLO-PALATAL FRICATIVE", id: "0255" },
  { symbol: "ʑ", desc: "VOICED ALVEOLO-PALATAL FRICATIVE", id: "0291" },
  { symbol: "w", desc: "VOICED LABIAL-VELAR APPROXIMANT", id: "0077" },
  { symbol: "ɺ", desc: "VOICED ALVEOLAR LATERAL FLAP", id: "027A" },
  { symbol: "ɥ", desc: "VOICED LABIAL-PALATAL APPROXIMANT", id: "0265" },
  { symbol: "ɧ", desc: "VOICELESS POSTALVEOLAR-VELAR FRICATIVE", id: "0267" },
  { symbol: "ʜ", desc: "VOICELESS EPIGLOTTAL FRICATIVE", id: "029C" },
  { symbol: "ʢ", desc: "VOICED EPIGLOTTAL FRICATIVE/APPROXIMANT", id: "02A2" },
  { symbol: "ʡ", desc: "EPIGLOTTAL PLOSIVE", id: "02A1" },
  // { symbol: "͜", desc: "TIE BAR (BELOW)", id: "035C" },
  // { symbol: "͡", desc: "TIE BAR (ABOVE)", id: "0361" },
  // { symbol: "̥", desc: "VOICELESS", id: "0325" },
  // { symbol: "̤", desc: "BREATHY VOICED", id: "0324" },
  // { symbol: "̪", desc: "DENTAL", id: "032A" },
  // { symbol: "̬", desc: "VOICED", id: "032C" },
  // { symbol: "̰", desc: "CREAKY VOICED", id: "0330" },
  // { symbol: "̺", desc: "APICAL", id: "033A" },
  // { symbol: "ʰ", desc: "ASPIRATED", id: "02B0" },
  // { symbol: "̼", desc: "LINGUOLABIAL", id: "033C" },
  // { symbol: "̻", desc: "LAMINAL", id: "033B" },
  // { symbol: "̹", desc: "MORE ROUNDED", id: "0339" },
  // { symbol: "ʷ", desc: "LABIALIZED", id: "02B7" },
  // { symbol: "̃", desc: "NASALIZED", id: "0303" },
  // { symbol: "̜", desc: "LESS ROUNDED", id: "031C" },
  // { symbol: "ʲ", desc: "PALATALIZED", id: "02B2" },
  // { symbol: "ⁿ", desc: "NASAL RELEASE", id: "207F" },
  // { symbol: "̟", desc: "ADVANCED", id: "031F" },
  // { symbol: "ˠ", desc: "VELARIZED", id: "02E0" },
  // { symbol: "ˡ", desc: "LATERAL RELEASE", id: "02E1" },
  // { symbol: "̠", desc: "RETRACTED", id: "0320" },
  // { symbol: "ˤ", desc: "PHARYNGEALIZED", id: "02E4" },
  // { symbol: "̚", desc: "NO AUDIBLE RELEASE", id: "031A" },
  // { symbol: "̈", desc: "CENTRALIZED", id: "0308" },
  // { symbol: "̴", desc: "VELARIZED OR PHARYNGEALIZED", id: "0334" },
  // { symbol: "̽", desc: "MID-CENTRALIZED", id: "033D" },
  // { symbol: "̝", desc: "RAISED", id: "031D" },
  // { symbol: "̩", desc: "SYLLABIC", id: "0329" },
  // { symbol: "̞", desc: "LOWERED", id: "031E" },
  // { symbol: "̯", desc: "NON-SYLLABIC", id: "032F" },
  // { symbol: "̘", desc: "ADVANCED TONGUE ROOT", id: "0318" },
  // { symbol: "˞", desc: "RHOTICITY", id: "02DE" },
  // { symbol: "̙", desc: "RETRACTED TONGUE ROOT", id: "0319" },
  { symbol: "i", desc: "CLOSE FRONT UNROUNDED VOWEL", id: "0069" },
  { symbol: "y", desc: "CLOSE FRONT ROUNDED VOWEL", id: "0079" },
  { symbol: "ɨ", desc: "CLOSE CENTRAL UNROUNDED VOWEL", id: "0268" },
  { symbol: "ʉ", desc: "CLOSE CENTRAL ROUNDED VOWEL", id: "0289" },
  { symbol: "ɯ", desc: "CLOSE BACK UNROUNDED VOWEL", id: "026F" },
  { symbol: "u", desc: "CLOSE BACK ROUNDED VOWEL", id: "0075" },
  { symbol: "ɪ", desc: "NEAR-CLOSE NEAR-FRONT UNROUNDED VOWEL", id: "026A" },
  { symbol: "ʏ", desc: "NEAR-CLOSE NEAR-FRONT ROUNDED VOWEL", id: "028F" },
  { symbol: "ʊ", desc: "NEAR-CLOSE NEAR-BACK ROUNDED VOWEL", id: "028A" },
  { symbol: "e", desc: "CLOSE-MID FRONT UNROUNDED VOWEL", id: "0065" },
  { symbol: "ø", desc: "CLOSE-MID FRONT ROUNDED VOWEL", id: "00F8" },
  { symbol: "ɘ", desc: "CLOSE-MID CENTRAL UNROUNDED VOWEL", id: "0258" },
  { symbol: "ɵ", desc: "CLOSE-MID CENTRAL ROUNDED VOWEL", id: "0275" },
  { symbol: "ɤ", desc: "CLOSE-MID BACK UNROUNDED VOWEL", id: "0264" },
  { symbol: "o", desc: "CLOSE-MID BACK ROUNDED VOWEL", id: "006F" },
  { symbol: "ə", desc: "MID CENTRAL VOWEL", id: "0259" },
  { symbol: "ɛ", desc: "OPEN-MID FRONT UNROUNDED VOWEL", id: "025B" },
  { symbol: "œ", desc: "OPEN-MID FRONT ROUNDED VOWEL", id: "0153" },
  { symbol: "ɜ", desc: "OPEN-MID CENTRAL UNROUNDED VOWEL", id: "025C" },
  { symbol: "ɞ", desc: "OPEN-MID CENTRAL ROUNDED VOWEL", id: "025E" },
  { symbol: "ʌ", desc: "OPEN-MID BACK UNROUNDED VOWEL", id: "028C" },
  { symbol: "ɔ", desc: "OPEN-MID BACK ROUNDED VOWEL", id: "0254" },
  { symbol: "æ", desc: "NEAR-OPEN FRONT UNROUNDED VOWEL", id: "00E6" },
  { symbol: "ɐ", desc: "NEAR-OPEN CENTRAL VOWEL", id: "0250" },
  { symbol: "a", desc: "OPEN FRONT UNROUNDED VOWEL", id: "0061" },
  { symbol: "ɶ", desc: "OPEN FRONT ROUNDED VOWEL", id: "0276" },
  { symbol: "ɑ", desc: "OPEN BACK UNROUNDED VOWEL", id: "0251" },
  { symbol: "ɒ", desc: "OPEN BACK ROUNDED VOWEL", id: "0252" },
  // { symbol: "ˈ", desc: "PRIMARY STRESS", id: "02C8" },
  // { symbol: "ˌ", desc: "SECONDARY STRESS", id: "02CC" },
  // { symbol: "ː", desc: "LONG", id: "02D0" },
  // { symbol: "ˑ", desc: "HALF-LONG", id: "02D1" },
  // { symbol: "̆", desc: "EXTRA-SHORT", id: "0306" },
  // { symbol: "|", desc: "MINOR (FOOT) GROUP", id: "007C" },
  // { symbol: "‖", desc: "MAJOR (INTONATION) GROUP", id: "2016" },
  // { symbol: ".", desc: "SYLLABLE BREAK", id: "002E" },
  // { symbol: "‿", desc: "LINKING (ABSENCE OF A BREAK)", id: "203F" },
  // { symbol: "̋", desc: "EXTRA HIGH LEVEL TONE (ACCENT MARK)", id: "030B" },
  // { symbol: "˥", desc: "EXTRA HIGH LEVEL TONE (CHAO LETTER)", id: "02E5" },
  // { symbol: "̌", desc: "RISING CONTOUR TONE (ACCENT MARK)", id: "030C" },
  // { symbol: "˩˥", desc: "RISING CONTOUR TONE (CHAO LETTER)", id: "02E9 + 02E5" },
  // { symbol: "́", desc: "HIGH LEVEL TONE (ACCENT MARK)", id: "0301" },
  // { symbol: "˦", desc: "HIGH LEVEL TONE (CHAO LETTER)", id: "02E6" },
  // { symbol: "̂", desc: "FALLING CONTOUR TONE (ACCENT MARK)", id: "0302" },
  // { symbol: "˥˩", desc: "FALLING CONTOUR TONE (CHAO LETTER)", id: "02E5 + 02E9" },
  // { symbol: "̄", desc: "MID LEVEL TONE (ACCENT MARK)", id: "0304" },
  // { symbol: "˧", desc: "MID LEVEL TONE (CHAO LETTER)", id: "02E7" },
  // { symbol: "᷄", desc: "HIGH RISING CONTOUR TONE (ACCENT MARK)", id: "1DC4" },
  // { symbol: "˧˥", desc: "HIGH RISING CONTOUR TONE (CHAO LETTER)", id: "02E7 + 02E5" },
  // { symbol: "̀", desc: "LOW LEVEL TONE (ACCENT MARK)", id: "0300" },
  // { symbol: "˨", desc: "LOW LEVEL TONE (CHAO LETTER)", id: "02E8" },
  // { symbol: "᷅", desc: "LOW RISING CONTOUR TONE (ACCENT MARK)", id: "1DC5" },
  // { symbol: "˩˧", desc: "LOW RISING CONTOUR TONE (CHAO LETTER)", id: "02E9 + 02E7" },
  // { symbol: "̏", desc: "EXTRA LOW LEVEL TONE (ACCENT MARK)", id: "030F" },
  // { symbol: "˩", desc: "EXTRA LOW LEVEL TONE (CHAO LETTER)", id: "02E9" },
  // { symbol: "᷈", desc: "RISING-FALLING CONTOUR TONE (ACCENT MARK)", id: "1DC8" },
  // { symbol: "˧˦˨", desc: "RISING-FALLING CONTOUR TONE (CHAO LETTER)", id: "02E7 + 02E6 + 02E8" },
  // { symbol: "ꜜ", desc: "DOWNSTEP", id: "A71C" },
  // { symbol: "↗", desc: "GLOBAL RISE", id: "2197" },
  // { symbol: "ꜛ", desc: "UPSTEP", id: "A71B" },
  // { symbol: "↘", desc: "GLOBAL FALL", id: "2198" },
]
